// <auto-generated />
using System;
using LIMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LIMS.Infrastructure.Migrations
{
    [DbContext(typeof(LimsDbContext))]
    [Migration("20260512095940_Phase1_MasterData")]
    partial class Phase1_MasterData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LIMS.Domain.Entities.CalibrationRecord", b =>
                {
                    b.Property<int>("CalibrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CalibrationId"));

                    b.Property<DateOnly>("CalibrationDate")
                        .HasColumnType("date");

                    b.Property<string>("CertificateRef")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("NextCalibrationDue")
                        .HasColumnType("date");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("SignatureId")
                        .HasColumnType("integer");

                    b.HasKey("CalibrationId");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("SignatureId");

                    b.ToTable("CalibrationRecords");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.ElectronicSignature", b =>
                {
                    b.Property<int>("SignatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SignatureId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SignedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("SignatureId");

                    b.HasIndex("UserId");

                    b.ToTable("ElectronicSignatures");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.FormTemplate", b =>
                {
                    b.Property<int>("FormTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FormTemplateId"));

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("EvidenceMandatory")
                        .HasColumnType("boolean");

                    b.Property<string>("FormCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FormType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LabId")
                        .HasColumnType("integer");

                    b.Property<string>("RegulatoryTier")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ShiftIntervalHrs")
                        .HasColumnType("integer");

                    b.Property<int?>("SignatureId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeSlots")
                        .HasColumnType("jsonb");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("FormTemplateId");

                    b.HasIndex("FormCode")
                        .IsUnique();

                    b.HasIndex("LabId");

                    b.HasIndex("SignatureId");

                    b.ToTable("FormTemplates");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.FormTemplateLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocationId"));

                    b.Property<int>("ColumnOrder")
                        .HasColumnType("integer");

                    b.Property<int>("FormTemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("SpecLimitId")
                        .HasColumnType("integer");

                    b.HasKey("LocationId");

                    b.HasIndex("FormTemplateId");

                    b.HasIndex("SpecLimitId");

                    b.ToTable("FormTemplateLocations");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.FormTemplateParameter", b =>
                {
                    b.Property<int>("FormTemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("ParameterId")
                        .HasColumnType("integer");

                    b.Property<int?>("ColumnFrequency")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.HasKey("FormTemplateId", "ParameterId");

                    b.HasIndex("ParameterId");

                    b.ToTable("FormTemplateParameters");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.Instrument", b =>
                {
                    b.Property<int>("InstrumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InstrumentId"));

                    b.Property<DateOnly>("CalibrationDue")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InstrumentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("InstrumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LabId")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("InstrumentId");

                    b.HasIndex("InstrumentCode")
                        .IsUnique();

                    b.HasIndex("LabId");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.InstrumentBreakdown", b =>
                {
                    b.Property<int>("BreakdownId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BreakdownId"));

                    b.Property<int>("InstrumentId")
                        .HasColumnType("integer");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("RaisedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("RaisedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("ReturnSignatureId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BreakdownId");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("RaisedBy");

                    b.HasIndex("ReturnSignatureId");

                    b.ToTable("InstrumentBreakdowns");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.InstrumentRepair", b =>
                {
                    b.Property<int>("RepairId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RepairId"));

                    b.Property<int>("BreakdownId")
                        .HasColumnType("integer");

                    b.Property<string>("PartsUsed")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("RepairDate")
                        .HasColumnType("date");

                    b.Property<string>("RepairDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Technician")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("RepairId");

                    b.HasIndex("BreakdownId");

                    b.ToTable("InstrumentRepairs");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.LabConfig", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConfigId"));

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LabId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ConfigId");

                    b.HasIndex("LabId", "ConfigKey")
                        .IsUnique();

                    b.ToTable("LabConfigs");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.Laboratory", b =>
                {
                    b.Property<int>("LabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LabId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LabName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LabType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("LabId");

                    b.ToTable("Laboratories");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.MasterDataAuditLog", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditId"));

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb");

                    b.Property<string>("OldValue")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("PerformedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("AuditId");

                    b.ToTable("MasterDataAuditLogs");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaterialId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ShelfLifeDays")
                        .HasColumnType("integer");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("MaterialId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.ParameterLookupRow", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RowId"));

                    b.Property<decimal>("InputValue1")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("InputValue2")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("LookupTableId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ResultValue")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("RowId");

                    b.HasIndex("LookupTableId");

                    b.ToTable("ParameterLookupRows");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.ParameterLookupTable", b =>
                {
                    b.Property<int>("LookupTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LookupTableId"));

                    b.Property<string>("InputCol1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("InputCol2")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LookupCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ResultCol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("LookupTableId");

                    b.HasIndex("LookupCode")
                        .IsUnique();

                    b.ToTable("ParameterLookupTables");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.SpecLimit", b =>
                {
                    b.Property<int>("SpecLimitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpecLimitId"));

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("OotMaxValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("OotMinValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("ParameterId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RegulatoryMax")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("RegulatoryMin")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int?>("RegulatoryTier")
                        .HasColumnType("integer");

                    b.Property<int?>("SignatureId")
                        .HasColumnType("integer");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("SpecLimitId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ParameterId");

                    b.HasIndex("SignatureId");

                    b.ToTable("SpecLimits");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.TestMethod", b =>
                {
                    b.Property<int>("MethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MethodId"));

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MethodCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MethodType")
                        .HasColumnType("text");

                    b.Property<int?>("SignatureId")
                        .HasColumnType("integer");

                    b.Property<string>("SopReference")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("MethodId");

                    b.HasIndex("MethodCode")
                        .IsUnique();

                    b.HasIndex("SignatureId");

                    b.ToTable("TestMethods");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.TestMethodParameter", b =>
                {
                    b.Property<int>("ParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ParameterId"));

                    b.Property<string>("CalcFormula")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ColumnFrequency")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormulaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstrumentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<int?>("LookupTableId")
                        .HasColumnType("integer");

                    b.Property<int>("MethodId")
                        .HasColumnType("integer");

                    b.Property<string>("ParameterCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("ParameterId");

                    b.HasIndex("LookupTableId");

                    b.HasIndex("MethodId");

                    b.ToTable("TestMethodParameters");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTenantAdmin")
                        .HasColumnType("boolean");

                    b.Property<int?>("LabId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId");

                    b.HasIndex("LabId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.UserTrainingRecord", b =>
                {
                    b.Property<int>("TrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrainingId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("MethodId")
                        .HasColumnType("integer");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("TrainingDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ValidUntil")
                        .HasColumnType("date");

                    b.HasKey("TrainingId");

                    b.HasIndex("MethodId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTrainingRecords");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.CalibrationRecord", b =>
                {
                    b.HasOne("LIMS.Domain.Entities.Instrument", "Instrument")
                        .WithMany("CalibrationRecords")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LIMS.Domain.Entities.ElectronicSignature", "Signature")
                        .WithMany()
                        .HasForeignKey("SignatureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Instrument");

                    b.Navigation("Signature");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.ElectronicSignature", b =>
                {
                    b.HasOne("LIMS.Domain.Entities.User", "User")
                        .WithMany("Signatures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.FormTemplate", b =>
                {
                    b.HasOne("LIMS.Domain.Entities.Laboratory", "Lab")
                        .WithMany("FormTemplates")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LIMS.Domain.Entities.ElectronicSignature", "Signature")
                        .WithMany()
                        .HasForeignKey("SignatureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Lab");

                    b.Navigation("Signature");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.FormTemplateLocation", b =>
                {
                    b.HasOne("LIMS.Domain.Entities.FormTemplate", "FormTemplate")
                        .WithMany("Locations")
                        .HasForeignKey("FormTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LIMS.Domain.Entities.SpecLimit", "SpecLimit")
                        .WithMany()
                        .HasForeignKey("SpecLimitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FormTemplate");

                    b.Navigation("SpecLimit");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.FormTemplateParameter", b =>
                {
                    b.HasOne("LIMS.Domain.Entities.FormTemplate", "FormTemplate")
                        .WithMany("TemplateParameters")
                        .HasForeignKey("FormTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LIMS.Domain.Entities.TestMethodParameter", "Parameter")
                        .WithMany()
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FormTemplate");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.Instrument", b =>
                {
                    b.HasOne("LIMS.Domain.Entities.Laboratory", "Lab")
                        .WithMany("Instruments")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.InstrumentBreakdown", b =>
                {
                    b.HasOne("LIMS.Domain.Entities.Instrument", "Instrument")
                        .WithMany("Breakdowns")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LIMS.Domain.Entities.User", "RaisedByUser")
                        .WithMany()
                        .HasForeignKey("RaisedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LIMS.Domain.Entities.ElectronicSignature", "ReturnSignature")
                        .WithMany()
                        .HasForeignKey("ReturnSignatureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Instrument");

                    b.Navigation("RaisedByUser");

                    b.Navigation("ReturnSignature");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.InstrumentRepair", b =>
                {
                    b.HasOne("LIMS.Domain.Entities.InstrumentBreakdown", "Breakdown")
                        .WithMany("Repairs")
                        .HasForeignKey("BreakdownId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Breakdown");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.LabConfig", b =>
                {
                    b.HasOne("LIMS.Domain.Entities.Laboratory", "Lab")
                        .WithMany("LabConfigs")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.ParameterLookupRow", b =>
                {
                    b.HasOne("LIMS.Domain.Entities.ParameterLookupTable", "LookupTable")
                        .WithMany("Rows")
                        .HasForeignKey("LookupTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LookupTable");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.SpecLimit", b =>
                {
                    b.HasOne("LIMS.Domain.Entities.Material", "Material")
                        .WithMany("SpecLimits")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LIMS.Domain.Entities.TestMethodParameter", "Parameter")
                        .WithMany("SpecLimits")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LIMS.Domain.Entities.ElectronicSignature", "Signature")
                        .WithMany()
                        .HasForeignKey("SignatureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Material");

                    b.Navigation("Parameter");

                    b.Navigation("Signature");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.TestMethod", b =>
                {
                    b.HasOne("LIMS.Domain.Entities.ElectronicSignature", "Signature")
                        .WithMany()
                        .HasForeignKey("SignatureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Signature");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.TestMethodParameter", b =>
                {
                    b.HasOne("LIMS.Domain.Entities.ParameterLookupTable", "LookupTable")
                        .WithMany()
                        .HasForeignKey("LookupTableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LIMS.Domain.Entities.TestMethod", "Method")
                        .WithMany("Parameters")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LookupTable");

                    b.Navigation("Method");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.User", b =>
                {
                    b.HasOne("LIMS.Domain.Entities.Laboratory", "Lab")
                        .WithMany()
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.UserTrainingRecord", b =>
                {
                    b.HasOne("LIMS.Domain.Entities.TestMethod", "Method")
                        .WithMany()
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LIMS.Domain.Entities.User", "User")
                        .WithMany("TrainingRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Method");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.FormTemplate", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("TemplateParameters");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.Instrument", b =>
                {
                    b.Navigation("Breakdowns");

                    b.Navigation("CalibrationRecords");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.InstrumentBreakdown", b =>
                {
                    b.Navigation("Repairs");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.Laboratory", b =>
                {
                    b.Navigation("FormTemplates");

                    b.Navigation("Instruments");

                    b.Navigation("LabConfigs");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.Material", b =>
                {
                    b.Navigation("SpecLimits");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.ParameterLookupTable", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.TestMethod", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.TestMethodParameter", b =>
                {
                    b.Navigation("SpecLimits");
                });

            modelBuilder.Entity("LIMS.Domain.Entities.User", b =>
                {
                    b.Navigation("Signatures");

                    b.Navigation("TrainingRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
