using LIMS.Domain.Enums;

namespace LIMS.Domain.Entities;

// Phase 2: Sample Registration — entry point for all LIMS lab work
public class Sample
{
    public int SampleId { get; set; }
    public string SampleNumber { get; set; } = default!;     // server-generated by ISampleIdFormatService (Contract 2)
    public int LabId { get; set; }
    public Laboratory Lab { get; set; } = default!;
    public int MaterialId { get; set; }
    public Material Material { get; set; } = default!;
    public string LotNumber { get; set; } = default!;
    public DateOnly MfgDate { get; set; }
    public DateOnly ExpDate { get; set; }
    public int SampleTypeId { get; set; }                     // FK → SampleType master table (Gap 2 fix)
    public SampleType SampleTypeNav { get; set; } = default!;
    public int? FormTemplateId { get; set; }                 // auto-selected by IFormTemplateSelectorService
    public FormTemplate? FormTemplate { get; set; }
    public SampleStatus Status { get; set; } = SampleStatus.Registered;
    public bool BarcodePrinted { get; set; } = false;
    public DateTimeOffset? BarcodePrintedAt { get; set; }
    public int? SrfSignatureId { get; set; }
    public ElectronicSignature? SrfSignature { get; set; }
    public DateTimeOffset? DueDate { get; set; }             // server-calculated from DB TAT config (Contract 2)
    public int AnalystId { get; set; }                       // ALCOA+ Attributable
    public User Analyst { get; set; } = default!;

    // ── Phase A: Sample receipt fields (R8) ──────────────────────────────
    public decimal? ReceivedTemp           { get; set; }     // °C at time of receipt
    public SampleCondition? SampleCondition { get; set; }   // OK | Damaged | Compromised
    public bool IsRush                     { get; set; } = false;
    public string? ExternalBatchId         { get; set; }    // MES/ERP batch reference

    // ── Phase A: Specification Engine audit trail ─────────────────────────
    // Records exactly which spec was applied and how — satisfies 21 CFR Part 11
    public int? SpecTemplateId             { get; set; }
    public SpecificationTemplate? SpecTemplate { get; set; }
    public string? SpecAssignedBy          { get; set; }    // 'System' (AutoMatch) or username (ManualOverride)
    public DateTimeOffset? SpecAssignedAt  { get; set; }
    public SpecAssignmentReason? SpecAssignmentReason { get; set; }  // AutoMatch|ManualOverride|NoTemplateFound

    public string CreatedBy { get; set; } = default!;
    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;

    public ICollection<BarcodePrintLog> PrintLogs { get; set; } = [];
    public ICollection<SampleCheckpoint> SampleCheckpoints { get; set; } = [];
    public ICollection<TestExecution> TestExecutions { get; set; } = [];
}

// Links checkpoints to samples — operator-selected at registration
public class SampleCheckpoint
{
    public int SampleCheckpointId { get; set; }
    public int SampleId { get; set; }
    public Sample Sample { get; set; } = default!;
    public int CheckpointId { get; set; }
    public Checkpoint Checkpoint { get; set; } = default!;
}

// 21 CFR 211.170: barcode label is chain-of-custody anchor; every print INSERT-only
public class BarcodePrintLog
{
    public int PrintId { get; set; }
    public int SampleId { get; set; }
    public Sample Sample { get; set; } = default!;
    public string PrintType { get; set; } = default!;        // AutoOnRegistration | Reprint
    public string PrintedBy { get; set; } = default!;
    public DateTimeOffset PrintedAt { get; set; } = DateTimeOffset.UtcNow;
    public string? Reason { get; set; }                      // required for Reprint
}
