using LIMS.Domain.Enums;

namespace LIMS.Domain.Entities;

// Phase 2: Sample Registration — entry point for all LIMS lab work
public class Sample
{
    public int SampleId { get; set; }
    public string SampleNumber { get; set; } = default!;     // server-generated by ISampleIdFormatService (Contract 2)
    public int LabId { get; set; }
    public Laboratory Lab { get; set; } = default!;
    public int MaterialId { get; set; }
    public Material Material { get; set; } = default!;
    public string LotNumber { get; set; } = default!;
    public DateOnly MfgDate { get; set; }
    public DateOnly ExpDate { get; set; }
    public int SampleTypeId { get; set; }                     // FK → SampleType master table (Gap 2 fix)
    public SampleType SampleTypeNav { get; set; } = default!;
    public int? FormTemplateId { get; set; }                 // auto-selected by IFormTemplateSelectorService
    public FormTemplate? FormTemplate { get; set; }
    public SampleStatus Status { get; set; } = SampleStatus.Registered;
    public bool BarcodePrinted { get; set; } = false;
    public DateTimeOffset? BarcodePrintedAt { get; set; }
    public int? SrfSignatureId { get; set; }
    public ElectronicSignature? SrfSignature { get; set; }
    public DateTimeOffset? DueDate { get; set; }             // server-calculated from DB TAT config (Contract 2)
    public int AnalystId { get; set; }                       // ALCOA+ Attributable
    public User Analyst { get; set; } = default!;
    public string CreatedBy { get; set; } = default!;
    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;

    public ICollection<BarcodePrintLog> PrintLogs { get; set; } = [];
}

// 21 CFR 211.170: barcode label is chain-of-custody anchor; every print INSERT-only
public class BarcodePrintLog
{
    public int PrintId { get; set; }
    public int SampleId { get; set; }
    public Sample Sample { get; set; } = default!;
    public string PrintType { get; set; } = default!;        // AutoOnRegistration | Reprint
    public string PrintedBy { get; set; } = default!;
    public DateTimeOffset PrintedAt { get; set; } = DateTimeOffset.UtcNow;
    public string? Reason { get; set; }                      // required for Reprint
}
