// <auto-generated />
using LIMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LIMS.Infrastructure.Migrations
{
    [DbContext(typeof(LimsDbContext))]
    [Migration("20260530120000_Patch_AdminTrainingRecords")]
    partial class Patch_AdminTrainingRecords
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
