// <auto-generated />
using LIMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LIMS.Infrastructure.Migrations
{
    [DbContext(typeof(LimsDbContext))]
    [Migration("20260522130000_Phase12_NormalizerViews")]
    partial class Phase12_NormalizerViews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Pure SQL migration — no model changes.
            // BuildTargetModel intentionally empty; model is unchanged from
            // 20260522124410_Fix_AdminPassword_For_Tests.
        }
    }
}
