// <auto-generated />
using LIMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LIMS.Infrastructure.Migrations
{
    [DbContext(typeof(LimsDbContext))]
    [Migration("20260530110000_Add_SampleLabel_TankSourceId")]
    partial class Add_SampleLabel_TankSourceId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Snapshot intentionally minimal — columns added via raw SQL in Up().
            // Full model snapshot is maintained in LimsDbContextModelSnapshot.cs.
        }
    }
}
