// <auto-generated />
using LIMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LIMS.Infrastructure.Migrations
{
    [DbContext(typeof(LimsDbContext))]
    [Migration("20260527090000_Patch_MissingColumns")]
    partial class Patch_MissingColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Snapshot intentionally minimal — this migration uses raw SQL only
        }
    }
}
